const DOMAIN = process.env.DOMAIN
const SUPABASE_URL = process.env.SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_KEY
// Server ports
const API_PORT = 3000
const AUTH_PORT = 4000
// Access tokens
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET
// Response status codes
const STATUS_UNAUTHORIZED = 401
const STATUS_FORBIDDEN = 403
const STATUS_BAD_GATEWAY = 400
const STATUS_INTERNAL_SERVER_ERROR = 500
const STATUS_CREATED = 201
// Access token expiry
const ACCESS_TOKEN_EXPIRY = '30m'
// Salt value
const SALT = 16

module.exports = {
  DOMAIN,
  SUPABASE_URL,
  SUPABASE_KEY,
  API_PORT,
  AUTH_PORT,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  STATUS_UNAUTHORIZED,
  STATUS_FORBIDDEN,
  STATUS_BAD_GATEWAY,
  STATUS_INTERNAL_SERVER_ERROR,
  STATUS_CREATED,
  ACCESS_TOKEN_EXPIRY,
  SALT,
}
